GET http://localhost:3001/api/persons/

###

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "id": 0,
    "name": "Ol2",
    "number": "123-456"
}

###

POST https://phonebook-1oyz.onrender.com/api/persons
Content-Type: application/json

{
    "id": 0,
    "name": "Ole2",
    "number": "123-456"
}
