GET http://localhost:3001/api/notes/

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "VSCode REAS client",
    "important": true
}

###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "content": "lol",
    "important": false
}

###
POST http://localhost:3001/api/notes/
content-type: application/json

{
    "content": "content with user 2",
    "important": true,
    "userId": "648ca30e70b0819ef3a855d0"
}

###

# @name response
post http://localhost:{{$dotenv PORT}}/api/login
Content-Type: application/json

{
    "username": "mluukkai",
    "password": "salainen"
}

###

@authToken = {{response.response.body.token}}

### 
POST http://localhost:{{$dotenv PORT}}/api/notes
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "content": "Use woken is simple, isn't?",
    "important": true
}
