# @name response
post http://localhost:{{$dotenv PORT}}/api/login
Content-Type: application/json

{
    "username": "mluukkai",
    "password": "salainen"
}

###

@authToken = {{response.response.body.token}}

###

GET http://localhost:{{$dotenv PORT}}/api/login
content-type: application/json
Authorization: Bearer {{authToken}}
